<a href="https://colab.research.google.com/github/dhanyab123/campingwithmachines/blob/main/ML_Zoomcamp_Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Homework 1

The questions can be found here: https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/01-intro/homework.md

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Answer 1 :

In [4]:
# numpy version
np.__version__

'1.19.5'

### Answer 2 :

In [5]:
# pandas version
pd.__version__

'1.1.5'

In [7]:
# reading data
data = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')
data

Make       Model  Year  ... city mpg  Popularity   MSRP
0          BMW  1 Series M  2011  ...       19        3916  46135
1          BMW    1 Series  2011  ...       19        3916  40650
2          BMW    1 Series  2011  ...       20        3916  36350
3          BMW    1 Series  2011  ...       18        3916  29450
4          BMW    1 Series  2011  ...       18        3916  34500
...        ...         ...   ...  ...      ...         ...    ...
11909    Acura         ZDX  2012  ...       16         204  46120
11910    Acura         ZDX  2012  ...       16         204  56670
11911    Acura         ZDX  2012  ...       16         204  50620
11912    Acura         ZDX  2013  ...       16         204  50920
11913  Lincoln      Zephyr  2006  ...       17          61  28995

[11914 rows x 16 columns]

### Answer 3 :

In [13]:
# separating data for bmw
bmw = data.loc[data['Make']=='BMW']

# finding avg
np.average(bmw.MSRP)

61546.76347305389

### Answer 4 :

In [27]:
# separating data for cars made on and after 2015
cars_2015 = data[data['Year'] >= 2015]

# looking at the data
cars_2015.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5995 entries, 32 to 11902
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               5995 non-null   object 
 1   Model              5995 non-null   object 
 2   Year               5995 non-null   int64  
 3   Engine Fuel Type   5995 non-null   object 
 4   Engine HP          5944 non-null   float64
 5   Engine Cylinders   5987 non-null   float64
 6   Transmission Type  5995 non-null   object 
 7   Driven_Wheels      5995 non-null   object 
 8   Number of Doors    5990 non-null   float64
 9   Market Category    4671 non-null   object 
 10  Vehicle Size       5995 non-null   object 
 11  Vehicle Style      5995 non-null   object 
 12  highway MPG        5995 non-null   int64  
 13  city mpg           5995 non-null   int64  
 14  Popularity         5995 non-null   int64  
 15  MSRP               5995 non-null   int64  
dtypes: float64(3), int64(5

In [31]:
# finding the number of null values in column
cars_2015['Engine HP'].isnull().sum()

51

### Answer 5 :

In [101]:
# finding avg (nan cause of null values)
np.average(data['Engine HP'])

nan

In [102]:
# separating the non null values
val = data.loc[data['Engine HP'].isnull() == False]

# finding avg
ehp_avg = np.average(val['Engine HP'])

In [103]:
# filling null values with avg
ehp = data['Engine HP'].fillna(ehp_avg)

In [104]:
# final avg
np.average(ehp)

249.38607007176023

In [105]:
# comparison
print('Mean Engine HP Before:', round(ehp_avg))
print('Mean Engine HP After:', round(np.average(ehp)))

Mean Engine HP Before: 249
Mean Engine HP After: 249


### Answer 6 :

In [55]:
rr = data[data['Make'] == 'Rolls-Royce']
rrv = rr[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [59]:
# removing duplicates
rrv.drop_duplicates()

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [60]:
# array without duplicates
X = np.array(rrv.drop_duplicates())

In [75]:
# transpose array
T = np.transpose(X)

In [64]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [76]:
T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [90]:
# matrix multiplication
XTX = np.matmul(T,X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [92]:
# inverse matrix
XTX_inv = np.linalg.inv(XTX)

# sum
XTX_inv.sum()

0.032212320677486125

### Answer 7 :

In [93]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [100]:
w = np.matmul(XTX_inv, T)
w = np.matmul(w, y)
w[0]

0.19989598183188978

---
